{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'c:\\\\Users\\\\manob\\\\Documents\\\\Kidney_Disease_Detection\\\\Kidney_Disease_Detection\\\\research'"
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "%pwd"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "os.chdir(\"../\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'c:\\\\Users\\\\manob\\\\Documents\\\\Kidney_Disease_Detection\\\\Kidney_Disease_Detection'"
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "%pwd\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "from dataclasses import dataclass\n",
    "from pathlib import Path\n",
    "\n",
    "\n",
    "@dataclass(frozen=True)\n",
    "class TrainingConfig:\n",
    "    root_dir: Path\n",
    "    trained_model_path: Path\n",
    "    updated_base_model_path: Path\n",
    "    training_data: Path\n",
    "    params_epochs: int\n",
    "    params_batch_size: int\n",
    "    params_is_augmentation: bool\n",
    "    params_image_size: list\n",
    "    params_learning_rate: float "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "c:\\Users\\manob\\Documents\\Kidney_Disease_Detection\\Kidney_Disease_Detection\\.conda\\Lib\\site-packages\\numpy\\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:\n",
      "c:\\Users\\manob\\Documents\\Kidney_Disease_Detection\\Kidney_Disease_Detection\\.conda\\Lib\\site-packages\\numpy\\.libs\\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll\n",
      "c:\\Users\\manob\\Documents\\Kidney_Disease_Detection\\Kidney_Disease_Detection\\.conda\\Lib\\site-packages\\numpy\\.libs\\libopenblas64__v0.3.21-gcc_10_3_0.dll\n",
      "  warnings.warn(\"loaded more than 1 DLL from .libs:\"\n"
     ]
    }
   ],
   "source": [
    "from cnnClassifier.constants import *\n",
    "from cnnClassifier.utils.common import read_yaml, create_directories\n",
    "import tensorflow as tf"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "class ConfigurationManager:\n",
    "    def __init__(\n",
    "        self,\n",
    "        config_filepath = CONFIG_FILE_PATH,\n",
    "        params_filepath = PARAMS_FILE_PATH):\n",
    "\n",
    "        self.config = read_yaml(config_filepath)\n",
    "        self.params = read_yaml(params_filepath)\n",
    "\n",
    "        create_directories([self.config.artifacts_root])\n",
    "\n",
    "\n",
    "    def get_training_config(self) -> TrainingConfig:\n",
    "        training = self.config.training\n",
    "\n",
    "        # Check for 'prepare_model' \n",
    "        if \"prepare_model\" not in self.config:\n",
    "            raise KeyError(\"Key 'prepare_model' is missing from config.yaml!\")\n",
    "\n",
    "        prepare_model = self.config.prepare_model  \n",
    "        params = self.params\n",
    "\n",
    "        training_data = Path(training.training_data)\n",
    "\n",
    "        create_directories([Path(training.root_dir)])\n",
    "\n",
    "        training_config = TrainingConfig(\n",
    "            root_dir=Path(training.root_dir),\n",
    "            trained_model_path=Path(training.trained_model_path),\n",
    "            updated_base_model_path=Path(prepare_model.base_model_path),  \n",
    "            training_data=training_data,\n",
    "            params_epochs=params.EPOCHS,\n",
    "            params_batch_size=params.BATCH_SIZE,\n",
    "            params_is_augmentation=params.AUGMENTATION,\n",
    "            params_image_size=params.IMAGE_SIZE,\n",
    "            log_dir=Path(training.log_dir),\n",
    "            params_learning_rate =params.LEARNING_RATE\n",
    "        )\n",
    "\n",
    "        return training_config"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import shutil\n",
    "import tensorflow as tf\n",
    "from pathlib import Path\n",
    "from cnnClassifier.entity.config_entity import TrainingConfig\n",
    "from tensorflow.keras.preprocessing.image import ImageDataGenerator\n",
    "from cnnClassifier.logger import logger \n",
    "from sklearn.utils.class_weight import compute_class_weight\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "\n",
    "class Training:\n",
    "    def __init__(self, config: TrainingConfig):\n",
    "        self.config = config\n",
    "\n",
    "    def get_base_model(self):\n",
    "        \n",
    "        \"\"\"Load and compile the base model for training\"\"\"\n",
    "        logger.info(\"Loading base model...\")\n",
    "        self.model = tf.keras.models.load_model(self.config.updated_base_model_path)\n",
    "\n",
    "        # Compile the model\n",
    "        self.model.compile(\n",
    "            optimizer=tf.keras.optimizers.Adam(learning_rate=self.config.params_learning_rate),\n",
    "            loss='binary_crossentropy',\n",
    "            metrics=['accuracy']\n",
    "        )\n",
    "\n",
    "        logger.info(\"Base model loaded and compiled successfully.\")\n",
    "\n",
    "\n",
    "\n",
    "    def train_valid_generator(self):\n",
    "        \"\"\"Prepare data generators for training and validation\"\"\"\n",
    "        logger.info(\"Initializing training and validation data generators...\")\n",
    "\n",
    "        datagenerator_kwargs = dict(\n",
    "            rescale=1./255,\n",
    "            validation_split=0.20\n",
    "        )\n",
    "\n",
    "        dataflow_kwargs = dict(\n",
    "            target_size=self.config.params_image_size[:-1],\n",
    "            batch_size=self.config.params_batch_size,\n",
    "            class_mode=\"binary\",  \n",
    "            interpolation=\"bilinear\"\n",
    "        )\n",
    "\n",
    "        valid_datagenerator = tf.keras.preprocessing.image.ImageDataGenerator(\n",
    "            **datagenerator_kwargs\n",
    "        )\n",
    "\n",
    "        # Path to both datasets\n",
    "        dataset_paths = [\n",
    "            os.path.join(self.config.training_data, \"Original Dataset\"),\n",
    "            os.path.join(self.config.training_data, \"Augmented Dataset\")\n",
    "        ]\n",
    "\n",
    "        # Create a combined dataset folder\n",
    "        combined_training_dir = \"artifacts/data_ingestion/Combined_Training_Data\"\n",
    "\n",
    "        if not os.path.exists(combined_training_dir):\n",
    "            os.makedirs(combined_training_dir, exist_ok=True)\n",
    "            os.makedirs(os.path.join(combined_training_dir, \"Stone\"), exist_ok=True)\n",
    "            os.makedirs(os.path.join(combined_training_dir, \"Non-Stone\"), exist_ok=True)\n",
    "\n",
    "        # Copy images from BOTH datasets\n",
    "        for dataset_path in dataset_paths:\n",
    "            for class_name in [\"Stone\", \"Non-Stone\"]:\n",
    "                src_folder = os.path.join(dataset_path, class_name)\n",
    "                dest_folder = os.path.join(combined_training_dir, class_name)\n",
    "\n",
    "                if os.path.exists(src_folder):\n",
    "                    for file in os.listdir(src_folder):\n",
    "                        src_file_path = os.path.join(src_folder, file)\n",
    "                        dest_file_path = os.path.join(dest_folder, file)\n",
    "\n",
    "                        # Avoid overwriting duplicate files by renaming\n",
    "                        if os.path.exists(dest_file_path):\n",
    "                            filename, ext = os.path.splitext(file)\n",
    "                            dest_file_path = os.path.join(dest_folder, f\"{filename}_copy{ext}\")\n",
    "\n",
    "                        shutil.copy(src_file_path, dest_file_path)\n",
    "\n",
    "        # Load from the newly created combined dataset\n",
    "        self.valid_generator = valid_datagenerator.flow_from_directory(\n",
    "            directory=combined_training_dir,\n",
    "            subset=\"validation\",\n",
    "            shuffle=False,\n",
    "            **dataflow_kwargs\n",
    "        )\n",
    "\n",
    "        if self.config.params_is_augmentation:\n",
    "            train_datagenerator = ImageDataGenerator(\n",
    "                rescale=1./255,\n",
    "                rotation_range=20,\n",
    "                zoom_range=0.2,\n",
    "                width_shift_range=0.1,\n",
    "                height_shift_range=0.1,\n",
    "                shear_range=0.1,\n",
    "                horizontal_flip=True,\n",
    "                validation_split=0.20\n",
    "            )\n",
    "        else:\n",
    "            train_datagenerator = ImageDataGenerator(\n",
    "                rescale=1./255,\n",
    "                validation_split=0.20\n",
    "            )\n",
    "\n",
    "        self.train_generator = train_datagenerator.flow_from_directory(\n",
    "            directory=combined_training_dir,\n",
    "            subset=\"training\",\n",
    "            shuffle=True,\n",
    "            **dataflow_kwargs\n",
    "        )\n",
    "\n",
    "        # Print dataset info\n",
    "        print(\"Training data classes:\", self.train_generator.class_indices)\n",
    "        print(\"Number of training samples:\", self.train_generator.samples)\n",
    "        print(\"Number of validation samples:\", self.valid_generator.samples)\n",
    "\n",
    "        logger.info(\"Data generators initialized successfully.\")\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "    def train(self):\n",
    "        \"\"\"Train the model with logging, Early Stopping, and Class Weights\"\"\"\n",
    "        logger.info(\"Starting model training...\")\n",
    "\n",
    "        self.steps_per_epoch = self.train_generator.samples // self.train_generator.batch_size\n",
    "        self.validation_steps = self.valid_generator.samples // self.valid_generator.batch_size\n",
    "\n",
    "        # Ensure log directory exists\n",
    "        log_dir = Path(self.config.root_dir) / \"logs\"\n",
    "        log_dir.mkdir(parents=True, exist_ok=True)\n",
    "\n",
    "        # Look in BOTH \"Original Dataset\" and \"Augmented Dataset\"\n",
    "        stone_count = 0\n",
    "        non_stone_count = 0\n",
    "        dataset_paths = [\n",
    "            os.path.join(self.config.training_data, \"Original Dataset\"),\n",
    "            os.path.join(self.config.training_data, \"Augmented Dataset\")\n",
    "        ]\n",
    "\n",
    "        for dataset_path in dataset_paths:\n",
    "            if os.path.exists(dataset_path):\n",
    "                stone_count += len(os.listdir(os.path.join(dataset_path, \"Stone\")))\n",
    "                non_stone_count += len(os.listdir(os.path.join(dataset_path, \"Non-Stone\")))\n",
    "\n",
    "        # Handle cases where folders don't exist\n",
    "        if stone_count == 0 or non_stone_count == 0:\n",
    "            raise FileNotFoundError(f\"One of the class folders (Stone or Non-Stone) is missing in {dataset_paths}\")\n",
    "\n",
    "        # Compute class weights\n",
    "        class_weights = compute_class_weight(\n",
    "            class_weight=\"balanced\",\n",
    "            classes=np.array([0, 1]),\n",
    "            y=[0] * non_stone_count + [1] * stone_count\n",
    "        )\n",
    "\n",
    "        class_weight_dict = {0: class_weights[0], 1: class_weights[1]}\n",
    "\n",
    "        # Early Stopping Callback\n",
    "        early_stopping = tf.keras.callbacks.EarlyStopping(\n",
    "            monitor=\"val_loss\",\n",
    "            patience=5,\n",
    "            restore_best_weights=True\n",
    "        )\n",
    "\n",
    "        # TensorBoard Callback\n",
    "        tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir=str(log_dir))\n",
    "\n",
    "        # Model Checkpoint Callback to save the best model during training\n",
    "        checkpoint = tf.keras.callbacks.ModelCheckpoint(\n",
    "            filepath=self.config.trained_model_path,\n",
    "            monitor=\"val_accuracy\",\n",
    "            save_best_only=True,\n",
    "            mode=\"max\",\n",
    "            verbose=1\n",
    "        )\n",
    "\n",
    "        try:\n",
    "            history = self.model.fit(\n",
    "            self.train_generator,\n",
    "            epochs=self.config.params_epochs,\n",
    "            steps_per_epoch=self.steps_per_epoch,\n",
    "            validation_steps=self.validation_steps,\n",
    "            validation_data=self.valid_generator,\n",
    "            class_weight=class_weight_dict,\n",
    "            callbacks=[early_stopping, tensorboard_callback, checkpoint]\n",
    "        )\n",
    "            \n",
    "            \n",
    "            logger.info(\"Model training completed successfully.\")\n",
    "\n",
    "            self.save_model(\n",
    "                path=self.config.trained_model_path,\n",
    "                model=self.model\n",
    "            )\n",
    "            logger.info(f\"Model saved at {self.config.trained_model_path}\")\n",
    "\n",
    "        except Exception as e:\n",
    "            logger.error(f\"Training failed due to: {e}\")\n",
    "            raise e\n",
    "        \n",
    "        # Plot training & validation accuracy/loss\n",
    "        try:\n",
    "            metrics_dir = Path(self.config.root_dir) / \"metrics\"\n",
    "            metrics_dir.mkdir(parents=True, exist_ok=True)\n",
    "            # Plot Accuracy\n",
    "            plt.figure(figsize=(8, 6))\n",
    "            plt.plot(history.history['accuracy'], label='Train Accuracy')\n",
    "            plt.plot(history.history['val_accuracy'], label='Validation Accuracy')\n",
    "            plt.title('Model Accuracy')\n",
    "            plt.xlabel('Epochs')\n",
    "            plt.ylabel('Accuracy')\n",
    "            plt.legend()\n",
    "            plt.grid(True)\n",
    "            plt.savefig(metrics_dir / 'accuracy.png')\n",
    "            plt.close()\n",
    "\n",
    "            # Plot Loss\n",
    "            plt.figure(figsize=(8, 6))\n",
    "            plt.plot(history.history['loss'], label='Train Loss')\n",
    "            plt.plot(history.history['val_loss'], label='Validation Loss')\n",
    "            plt.title('Model Loss')\n",
    "            plt.xlabel('Epochs')\n",
    "            plt.ylabel('Loss')\n",
    "            plt.legend()\n",
    "            plt.grid(True)\n",
    "            plt.savefig(metrics_dir / 'loss.png')\n",
    "            plt.close()\n",
    "\n",
    "            logger.info(f\"Training metrics plotted and saved to {metrics_dir}\")\n",
    "\n",
    "        except Exception as plot_err:\n",
    "            logger.warning(f\"Could not plot training metrics due to: {plot_err}\")\n",
    "\n",
    "        \n",
    "    def save_model(self, path: Path, model: tf.keras.Model):\n",
    "        \"\"\"Save the trained model to a given path.\"\"\"\n",
    "        model.save(path)\n",
    "        logger.info(f\"Model saved successfully at: {path}\")       \n",
    "        \n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[2025-03-25 16:10:36,140: INFO: common: yaml file: config\\config.yaml loaded successfully]\n",
      "[2025-03-25 16:10:36,142: INFO: common: yaml file: params.yaml loaded successfully]\n",
      "[2025-03-25 16:10:36,144: INFO: common: created directory at: artifacts]\n",
      "[2025-03-25 16:10:36,147: INFO: common: created directory at: artifacts\\training]\n",
      "[2025-03-25 16:10:36,148: INFO: 1202200536: Loading base model...]\n",
      "[2025-03-25 16:10:36,780: WARNING: hdf5_format: No training configuration found in the save file, so the model was *not* compiled. Compile it manually.]\n",
      "[2025-03-25 16:10:36,784: INFO: 1202200536: Base model loaded and compiled successfully.]\n",
      "[2025-03-25 16:10:36,791: INFO: 1202200536: Initializing training and validation data generators...]\n",
      "Found 7763 images belonging to 2 classes.\n",
      "Found 31058 images belonging to 2 classes.\n",
      "Training data classes: {'Non-Stone': 0, 'Stone': 1}\n",
      "Number of training samples: 31058\n",
      "Number of validation samples: 7763\n",
      "[2025-03-25 16:11:14,416: INFO: 1202200536: Data generators initialized successfully.]\n",
      "[2025-03-25 16:11:14,416: INFO: 1202200536: Starting model training...]\n",
      "Epoch 1/40\n",
      "970/970 [==============================] - ETA: 0s - loss: 0.7095 - accuracy: 0.5693\n",
      "Epoch 1: val_accuracy improved from -inf to 0.51188, saving model to artifacts\\training\\model.h5\n",
      "970/970 [==============================] - 1801s 2s/step - loss: 0.7095 - accuracy: 0.5693 - val_loss: 0.8169 - val_accuracy: 0.5119\n",
      "Epoch 2/40\n",
      "970/970 [==============================] - ETA: 0s - loss: 0.6374 - accuracy: 0.6352\n",
      "Epoch 2: val_accuracy improved from 0.51188 to 0.58058, saving model to artifacts\\training\\model.h5\n",
      "970/970 [==============================] - 1500s 2s/step - loss: 0.6374 - accuracy: 0.6352 - val_loss: 0.7134 - val_accuracy: 0.5806\n",
      "Epoch 3/40\n",
      "970/970 [==============================] - ETA: 0s - loss: 0.5900 - accuracy: 0.6841\n",
      "Epoch 3: val_accuracy did not improve from 0.58058\n",
      "970/970 [==============================] - 1493s 2s/step - loss: 0.5900 - accuracy: 0.6841 - val_loss: 0.6960 - val_accuracy: 0.5692\n",
      "Epoch 4/40\n",
      "970/970 [==============================] - ETA: 0s - loss: 0.5213 - accuracy: 0.7401\n",
      "Epoch 4: val_accuracy did not improve from 0.58058\n",
      "970/970 [==============================] - 1483s 2s/step - loss: 0.5213 - accuracy: 0.7401 - val_loss: 0.7429 - val_accuracy: 0.5486\n",
      "Epoch 5/40\n",
      "970/970 [==============================] - ETA: 0s - loss: 0.4271 - accuracy: 0.8035\n",
      "Epoch 5: val_accuracy improved from 0.58058 to 0.72443, saving model to artifacts\\training\\model.h5\n",
      "970/970 [==============================] - 1488s 2s/step - loss: 0.4271 - accuracy: 0.8035 - val_loss: 0.4534 - val_accuracy: 0.7244\n",
      "Epoch 6/40\n",
      "970/970 [==============================] - ETA: 0s - loss: 0.3490 - accuracy: 0.8486\n",
      "Epoch 6: val_accuracy improved from 0.72443 to 0.72624, saving model to artifacts\\training\\model.h5\n",
      "970/970 [==============================] - 1489s 2s/step - loss: 0.3490 - accuracy: 0.8486 - val_loss: 0.4880 - val_accuracy: 0.7262\n",
      "Epoch 7/40\n",
      "970/970 [==============================] - ETA: 0s - loss: 0.2921 - accuracy: 0.8816\n",
      "Epoch 7: val_accuracy improved from 0.72624 to 0.83716, saving model to artifacts\\training\\model.h5\n",
      "970/970 [==============================] - 2385s 2s/step - loss: 0.2921 - accuracy: 0.8816 - val_loss: 0.3431 - val_accuracy: 0.8372\n",
      "Epoch 8/40\n",
      "970/970 [==============================] - ETA: 0s - loss: 0.2635 - accuracy: 0.8944\n",
      "Epoch 8: val_accuracy improved from 0.83716 to 0.86596, saving model to artifacts\\training\\model.h5\n",
      "970/970 [==============================] - 3371s 3s/step - loss: 0.2635 - accuracy: 0.8944 - val_loss: 0.3245 - val_accuracy: 0.8660\n",
      "Epoch 9/40\n",
      "970/970 [==============================] - ETA: 0s - loss: 0.2410 - accuracy: 0.9048\n",
      "Epoch 9: val_accuracy did not improve from 0.86596\n",
      "970/970 [==============================] - 1478s 2s/step - loss: 0.2410 - accuracy: 0.9048 - val_loss: 0.3400 - val_accuracy: 0.8657\n",
      "Epoch 10/40\n",
      "970/970 [==============================] - ETA: 0s - loss: 0.2236 - accuracy: 0.9141\n",
      "Epoch 10: val_accuracy improved from 0.86596 to 0.86686, saving model to artifacts\\training\\model.h5\n",
      "970/970 [==============================] - 1477s 2s/step - loss: 0.2236 - accuracy: 0.9141 - val_loss: 0.3282 - val_accuracy: 0.8669\n",
      "Epoch 11/40\n",
      "970/970 [==============================] - ETA: 0s - loss: 0.2033 - accuracy: 0.9206\n",
      "Epoch 11: val_accuracy did not improve from 0.86686\n",
      "970/970 [==============================] - 1478s 2s/step - loss: 0.2033 - accuracy: 0.9206 - val_loss: 0.4315 - val_accuracy: 0.7917\n",
      "Epoch 12/40\n",
      "970/970 [==============================] - ETA: 0s - loss: 0.1962 - accuracy: 0.9239\n",
      "Epoch 12: val_accuracy did not improve from 0.86686\n",
      "970/970 [==============================] - 1468s 2s/step - loss: 0.1962 - accuracy: 0.9239 - val_loss: 0.3717 - val_accuracy: 0.8231\n",
      "Epoch 13/40\n",
      "970/970 [==============================] - ETA: 0s - loss: 0.1853 - accuracy: 0.9277\n",
      "Epoch 13: val_accuracy did not improve from 0.86686\n",
      "970/970 [==============================] - 1451s 1s/step - loss: 0.1853 - accuracy: 0.9277 - val_loss: 0.3935 - val_accuracy: 0.8072\n",
      "[2025-03-25 22:23:56,639: INFO: 1202200536: Model training completed successfully.]\n",
      "[2025-03-25 22:23:56,910: INFO: 1202200536: Model saved successfully at: artifacts\\training\\model.h5]\n",
      "[2025-03-25 22:23:56,911: INFO: 1202200536: Model saved at artifacts\\training\\model.h5]\n",
      "[2025-03-25 22:23:57,329: INFO: 1202200536: Training metrics plotted and saved to artifacts\\training\\metrics]\n"
     ]
    }
   ],
   "source": [
    "try: \n",
    "    config = ConfigurationManager()\n",
    "    training_config = config.get_training_config()  \n",
    "    training = Training(config=training_config)\n",
    "    training.get_base_model()\n",
    "    training.train_valid_generator()\n",
    "    training.train()\n",
    "except Exception as e:\n",
    "    logger.exception(e)\n",
    "    raise e"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.11"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
